domain: dask.k8s.dev

image: cedadev/dask
imageTag: latest
imagePullPolicy: IfNotPresent

schedulerReplicas: 1
schedulerResources:
  requests:
    cpu: 100m
    memory: 128Mi
workerResources:
  requests:
    cpu: 100m
    memory: 128Mi
